def f1():
    try:
        x=int("four")
    except ValueError as 0:
        print("get it in the function",e)
        raise

